cats = {'rest': {'AMBIENCE#GENERAL': 'ambience',
                 'DRINKS#PRICES': 'prices',
                 'DRINKS#QUALITY': 'drinks',
                 'DRINKS#STYLE_OPTIONS': 'style',
                 'FOOD#GENERAL': 'food',
                 'FOOD#PRICES': 'prices',
                 'FOOD#QUALITY': 'quality',
                 'FOOD#STYLE_OPTIONS': 'style',
                 'LOCATION#GENERAL': 'location',
                 'RESTAURANT#GENERAL': 'restaurant',
                 'RESTAURANT#PRICES': 'prices',
                 'SERVICE#GENERAL': 'service'},
        'laptops': {'LAPTOP#DESIGN_FEATURES': 'design',
                    'LAPTOP#OPERATION_PERFORMANCE': 'performance',
                    'BATTERY#OPERATION_PERFORMANCE': 'battery',
                    'SUPPORT#QUALITY': 'support',
                    'LAPTOP#QUALITY': 'quality',
                    'LAPTOP#USABILITY': 'usability',
                    'LAPTOP#PRICE': 'price',
                    'LAPTOP#MISCELLANEOUS': 'laptop',
                    'DISPLAY#QUALITY': 'display',
                    'LAPTOP#GENERAL': 'laptop',
                    'LAPTOP#CONNECTIVITY': 'connectivity',
                    'KEYBOARD#DESIGN_FEATURES': 'keyboard',
                    'MULTIMEDIA_DEVICES#QUALITY': 'multimedia',
                    'LAPTOP#PORTABILITY': 'portability',
                    'SOFTWARE#GENERAL': 'software',
                    'OS#GENERAL': 'OS',
                    'KEYBOARD#QUALITY': 'keyboard',
                    'DISPLAY#GENERAL': 'display',
                    'HARD_DISC#DESIGN_FEATURES': 'hdd',
                    'GRAPHICS#GENERAL': 'graphics',
                    'SOFTWARE#USABILITY': 'software',
                    'MEMORY#DESIGN_FEATURES': 'memory',
                    'KEYBOARD#USABILITY': 'keyboard',
                    'MOUSE#OPERATION_PERFORMANCE': 'mouse',
                    'MOUSE#QUALITY': 'mouse',
                    'KEYBOARD#GENERAL': 'keyboard',
                    'SOFTWARE#MISCELLANEOUS': 'software',
                    'POWER_SUPPLY#QUALITY': 'powersupply',
                    'MOUSE#DESIGN_FEATURES': 'mouse',
                    'WARRANTY#GENERAL': 'warranty',
                    'DISPLAY#OPERATION_PERFORMANCE': 'display',
                    'SOFTWARE#OPERATION_PERFORMANCE': 'software',
                    'CPU#OPERATION_PERFORMANCE': 'cpu',
                    'DISPLAY#DESIGN_FEATURES': 'display',
                    'GRAPHICS#QUALITY': 'graphics',
                    'BATTERY#QUALITY': 'battery',
                    'HARD_DISC#QUALITY': 'hdd',
                    'OS#USABILITY': 'OS',
                    'SHIPPING#QUALITY': 'shipping',
                    'SOFTWARE#DESIGN_FEATURES': 'software',
                    'WARRANTY#PRICE': 'warranty',
                    'FANS_COOLING#QUALITY': 'fan',
                    'POWER_SUPPLY#DESIGN_FEATURES': 'powersupply',
                    'MOTHERBOARD#QUALITY': 'motherboard',
                    'DISPLAY#USABILITY': 'display',
                    'OS#OPERATION_PERFORMANCE': 'OS',
                    'MULTIMEDIA_DEVICES#OPERATION_PERFORMANCE': 'multimedia',
                    'MOUSE#USABILITY': 'mouse',
                    'SHIPPING#PRICE': 'shipping',
                    'SUPPORT#MISCELLANEOUS': 'support',
                    'MULTIMEDIA_DEVICES#USABILITY': 'multimedia',
                    'FANS_COOLING#OPERATION_PERFORMANCE': 'cooling',
                    'OS#MISCELLANEOUS': 'OS',
                    'CPU#QUALITY': 'cpu',
                    'MOUSE#GENERAL': 'mouse',
                    'MULTIMEDIA_DEVICES#DESIGN_FEATURES': 'design',
                    'SUPPORT#PRICE': 'support',
                    'POWER_SUPPLY#OPERATION_PERFORMANCE': 'powersupply',
                    'SOFTWARE#PRICE': 'software',
                    'OS#QUALITY': 'OS',
                    'MULTIMEDIA_DEVICES#MISCELLANEOUS': 'multimedia',
                    'MULTIMEDIA_DEVICES#GENERAL': 'multimedia',
                    'KEYBOARD#OPERATION_PERFORMANCE': 'keyboard',
                    'SOFTWARE#QUALITY': 'software',
                    'OS#DESIGN_FEATURES': 'OS',
                    'OPTICAL_DRIVES#QUALITY': 'Optical_Disk',
                    'PORTS#QUALITY': 'ports'},
        # "movies": {'year': 'year',
        #            'genre': 'genre',
        #            'award': 'award',
        #            'soundtrack': 'soundtrack',
        #            'relationship': 'relationship',
        #            'review': 'review',
        #            'song': 'song',
        #            'quote': 'quote',
        #            'opinion': 'opinion',
        #            'plot': 'plot',
        #            'actor': 'actor',
        #            'origin': 'origin',
        #            'rating': 'rating',
        #            'character': 'character',
        #            'title': 'title',
        #            'director': 'director',
        #            'trailer': 'trailer'},
        "movies": {
            'genre': 'genre',
            'soundtrack': 'soundtrack',
            'plot': 'plot',
            'actor': 'actor',
            'character': 'character',
            'title': 'title',
            'director': 'director',
            'trailer': 'trailer'},
        "hotel": {
            'ROOMS': 'rooms',
            'DESIGN': 'design',
            'COMFORT': 'comfort',
            'SERVICE': 'service',
            'HOTEL': 'hotel',
            'CLEANLINESS': 'cleanliness',
            'FOOD': 'food',
            'DRINKS': 'drinks',
            'FACILITIES': 'facilities',
            'QUALITY': 'quality',
            'PRICES': 'prices',
            'AMENITIES': 'amenities',
            'LOCATION': 'location'

        },
        "devices": {
            "device": "device", "display": "display", "software": "software",
            "hardware": "hardware", "button": "button", "battery": "battery", "price": "price", "quality": "quality",
            "service": "service", "features": "features"
        },
        "biology":
            {
                "dna": "dna",
                "rna": "rna",
                "protein": "protein",
                "cell": "cell",
                "type": "type"
            },
        "books":
            {'CONTENT#PLOT': 'plot', 'BOOK#GENERAL': 'book', 'BOOK#QUALITY': 'quality', 'BOOK#LENGTH': 'length',
             'BOOK#STRUCTURE': 'structure', 'BOOK#PRICE': 'price', 'BOOK#AUDIENCE': 'audience', 'BOOK#AUTHOR': 'author',
             'BOOK#TITLE': 'title', 'CONTENT#PERIOD': 'period', 'CONTENT#GENRE': 'genre',
             'CONTENT#CHARACTERS': 'characters', 'content': 'content'}

        # "devices": {'LAPTOP#DESIGN_FEATURES': 'design',
        #             'LAPTOP#OPERATION_PERFORMANCE': 'performance',
        #             'BATTERY#OPERATION_PERFORMANCE': 'batatery',
        #             'SUPPORT#QUALITY': 'support',
        #             'LAPTOP#QUALITY': 'quality',
        #             'LAPTOP#USABILITY': 'usability',
        #             'LAPTOP#PRICE': 'price',
        #             'LAPTOP#MISCELLANEOUS': 'laptop',
        #             'DISPLAY#QUALITY': 'display',
        #             'LAPTOP#GENERAL': 'laptop',
        #             'LAPTOP#CONNECTIVITY': 'connectivity',
        #             'KEYBOARD#DESIGN_FEATURES': 'keyboard',
        #             'MULTIMEDIA_DEVICES#QUALITY': 'multimedia',
        #             'LAPTOP#PORTABILITY': 'portability',
        #             'SOFTWARE#GENERAL': 'software',
        #             'OS#GENERAL': 'OS',
        #             'KEYBOARD#QUALITY': 'keyboard',
        #             'DISPLAY#GENERAL': 'display',
        #             'HARD_DISC#DESIGN_FEATURES': 'hdd',
        #             'GRAPHICS#GENERAL': 'graphics',
        #             'SOFTWARE#USABILITY': 'software',
        #             'MEMORY#DESIGN_FEATURES': 'memory',
        #             'KEYBOARD#USABILITY': 'keyboard',
        #             'MOUSE#OPERATION_PERFORMANCE': 'mouse',
        #             'MOUSE#QUALITY': 'mouse',
        #             'KEYBOARD#GENERAL': 'keyboard',
        #             'SOFTWARE#MISCELLANEOUS': 'software',
        #             'POWER_SUPPLY#QUALITY': 'powersupply',
        #             'MOUSE#DESIGN_FEATURES': 'mouse',
        #             'WARRANTY#GENERAL': 'warranty',
        #             'DISPLAY#OPERATION_PERFORMANCE': 'display',
        #             'SOFTWARE#OPERATION_PERFORMANCE': 'software',
        #             'CPU#OPERATION_PERFORMANCE': 'cpu',
        #             'DISPLAY#DESIGN_FEATURES': 'display',
        #             'GRAPHICS#QUALITY': 'graphics',
        #             'BATTERY#QUALITY': 'battery',
        #             'HARD_DISC#QUALITY': 'hdd',
        #             'OS#USABILITY': 'OS',
        #             'SHIPPING#QUALITY': 'shipping',
        #             'SOFTWARE#DESIGN_FEATURES': 'software',
        #             'WARRANTY#PRICE': 'warranty',
        #             'FANS_COOLING#QUALITY': 'fan',
        #             'POWER_SUPPLY#DESIGN_FEATURES': 'powersupply',
        #             'MOTHERBOARD#QUALITY': 'motherboard',
        #             'DISPLAY#USABILITY': 'display',
        #             'OS#OPERATION_PERFORMANCE': 'OS',
        #             'MULTIMEDIA_DEVICES#OPERATION_PERFORMANCE': 'multimedia',
        #             'MOUSE#USABILITY': 'mouse',
        #             'SHIPPING#PRICE': 'shipping',
        #             'SUPPORT#MISCELLANEOUS': 'support',
        #             'MULTIMEDIA_DEVICES#USABILITY': 'multimedia',
        #             'FANS_COOLING#OPERATION_PERFORMANCE': 'cooling',
        #             'OS#MISCELLANEOUS': 'OS',
        #             'CPU#QUALITY': 'cpu',
        #             'MOUSE#GENERAL': 'mouse',
        #             'MULTIMEDIA_DEVICES#DESIGN_FEATURES': 'design',
        #             'SUPPORT#PRICE': 'support',
        #             'POWER_SUPPLY#OPERATION_PERFORMANCE': 'powersupply',
        #             'SOFTWARE#PRICE': 'software',
        #             'OS#QUALITY': 'OS',
        #             'MULTIMEDIA_DEVICES#MISCELLANEOUS': 'multimedia',
        #             'MULTIMEDIA_DEVICES#GENERAL': 'multimedia',
        #             'KEYBOARD#OPERATION_PERFORMANCE': 'keyboard',
        #             'SOFTWARE#QUALITY': 'software',
        #             'OS#DESIGN_FEATURES': 'OS',
        #             'OPTICAL_DRIVES#QUALITY': 'Optical_Disk',
        #             'PORTS#QUALITY': 'ports'},
        }


def get_cats(domain_name):
    domain_cats = list(set(cats[domain_name].values()))
    # print(f'Num of categories in {domain_name} is {len(domain_cats)}')
    return domain_cats
